spring:
  jpa:
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    favicon:
      enabled: false
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
   
---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/common?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    
server:
  port: 8880
    
